heat_template_version: 2015-04-30

description: >
  This template will create a VM (docker host) and places a docker registry container
  inside.

parameters:

  hostname:
    type: string
    description: Server name, docke host or registry.

  domain:
    type: string
    description: Domain name. (i.e eurocloud.es)

  registry_user:
    type: string
    description: Username of your private account.
    default: ''

  registry_password:
    type: string
    description: Password of your private account.
    hidden: true
    default: ''

  use_redis:
    type: boolean
    description: Use redis as cache backend, if false then inmemory will be used.
    default: false

  docker_mtu:
    type: number
    description: MTU.
    default: 1400

  server_key:
    type: string
    description: Name of the SSH keypair registered with Nova
    constraints:
    - custom_constraint: nova.keypair

  server_image:
    type: string
    default: "CoreOS-1068.6.0"
    description: Glance image used to boot the server
    constraints:
    - allowed_values: ["CoreOS-1068.6.0"]
    - custom_constraint: glance.image

  server_flavor:
    type: string
    default: m1.medium
    description: Server flavor
    constraints:
    - custom_constraint: nova.flavor

  fip_network:
    type: string
    default: PUBLIC-ACCESS-POOL-2
    constraints:
    - allowed_values: ['PUBLIC-ACCESS-POOL-1', 'PUBLIC-ACCESS-POOL-2']
    - custom_constraint: neutron.network
    description: Pool of floating ip addresses

  volume_size:
    type: number
    description: The size of attached volume for docker registry.
    default: 20

resources:

  wait_handle:
    type: OS::Heat::WaitConditionHandle

  wait_condition:
    type: OS::Heat::WaitCondition
    properties:
      handle: { get_resource: wait_handle }
      timeout: 10000

  secret:
    type: OS::Heat::RandomString
    properties:
      length: 8

  redis_password:
    type: OS::Heat::RandomString
    properties:
      length: 8

  server:
    type: OS::Nova::Server
    depends_on:
    - volume
    properties:
      image: { get_param: server_image }
      flavor: { get_param: server_flavor }
      key_name: {get_param: server_key }
      user_data_format: RAW
      user_data: { get_resource: cloud_config_init}

  cloud_config_init:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ungrouped
      config:
        str_replace:
          template: { get_file: files/registry/coreos/cloud-config.yaml }
          params:
            "$secret$": { get_attr: [ secret, value ] }
            "$registry_user$": { get_param: registry_user }
            "$registry_password$": { get_param: registry_password }
            "$use_redis$": { get_param: use_redis }
            "$redis_password$": { get_attr: [ redis_password, value ] }
            "$domain$": { get_param: domain }
            "$hostname$": { get_param: hostname }
            "$mtu$": { get_param: docker_mtu }
            "$wc_notify$": { get_attr: [ wait_handle, curl_cli ] }

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
       floating_network: { get_param: fip_network }

  floating_ip_association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: floating_ip }
      server_id: { get_resource: server }

  volume:
    type: OS::Cinder::Volume
    properties:
      size: { get_param: volume_size }

  volume_attach:
    type: OS::Cinder::VolumeAttachment
    properties:
      instance_uuid: { get_resource: server }
      volume_id: { get_resource: volume }
      mountpoint: /dev/vdb

outputs:

  wc_data:
    value: { get_attr: [ wait_condition, data] }
  registry_ips:
    value:
     - { get_attr: [ server, addresses ] }
  secret:
    value: { get_attr: [ secret, value ]}
  redis:
    value:
     - { get_param: use_redis }
     - { get_attr: [ redis_password, value ]}
