#cloud-config
hostname: "$hostname$"
write_files:
  - path: "/home/root/registry_certs/domain.crt"
    permissions: "0644"
    owner: "root"
    content: |
      -----BEGIN CERTIFICATE-----
      MIICTDCCAbWgAwIBAgIJAIuw7+/IF82dMA0GCSqGSIb3DQEBBQUAMD8xCzAJBgNV
      BAYTAkVTMQswCQYDVQQIDAJNQTEPMA0GA1UEBwwGTWFkcmlkMRIwEAYDVQQKDAlF
      dXJvQ2xvdWQwHhcNMTYxMDE4MTUwODE0WhcNMTYxMTE3MTUwODE0WjA/MQswCQYD
      VQQGEwJFUzELMAkGA1UECAwCTUExDzANBgNVBAcMBk1hZHJpZDESMBAGA1UECgwJ
      RXVyb0Nsb3VkMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDg8yqzo3p2SGOx
      b00MP3ZKaAp02NDqNTkbIinXmL5IdebBzm7il4UzPjHflXn9s1BepmKsUi2Ekdxf
      BIumEwMc/Si4BTS6X9tbzxdqWDkILZR3zjeD0FnrG46yeiZLoWyo7nc2qm+8tDp4
      Xr9fl+LiMgYSf9+UiLC5q1VW3Qxk2wIDAQABo1AwTjAdBgNVHQ4EFgQU/xqQaATs
      I74zqbm2PWzB8S15u4cwHwYDVR0jBBgwFoAU/xqQaATsI74zqbm2PWzB8S15u4cw
      DAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQUFAAOBgQAENBqI2UgCY5aYa0mdxBog
      DbvHxkJv9d4OOpsY+L1E5Y/2CURd9ZDtcRLM9PpdF5la90OiUkDe1iroG5SFcnzo
      lTyBhuOrgsKKFH85BulZ28lNJX4vWlTY8aUPValXSgv2+3p4weRqst8mufjvntFG
      wLILnyEBVtGUDZATr0bd+Q==
      -----END CERTIFICATE-----
  - path: "/home/root/registry_certs/domain.key"
    permissions: "0600"
    owner: "root"
    content: |
      -----BEGIN RSA PRIVATE KEY-----
      MIICXgIBAAKBgQDg8yqzo3p2SGOxb00MP3ZKaAp02NDqNTkbIinXmL5IdebBzm7i
      l4UzPjHflXn9s1BepmKsUi2EkdxfBIumEwMc/Si4BTS6X9tbzxdqWDkILZR3zjeD
      0FnrG46yeiZLoWyo7nc2qm+8tDp4Xr9fl+LiMgYSf9+UiLC5q1VW3Qxk2wIDAQAB
      AoGBAI4sgmepQkQx+nhxnSPJlGzwlvNE+b2dR+uDSyjNjC5l/iOt4l1qYLCDdagX
      ZFPZmklIJgM9qTEpszuGtvCPAZ6Ib58rO63aYoS3PyvFPXmfN7elQdKMntJmTZKj
      KnqtrrJktbs/qRn918TtnDF+agfdoDEor3mYAMUvA7hMNe1BAkEA81JevwisbXiR
      8uD1jcou8AG0O7NI+U9/uQ48GBDEMscErqyYdpy0QawZYwUIgzoNXayz8Nd9DuB0
      knu+eLK/oQJBAOyrvK5jOgs6nXLyuxjOPpoEqgQwwg2MxWCcWummvUszLFcHdvRH
      9OrqXkhXAeqqlbq0wsgPj+eplduziMGDQvsCQQCTgdHyWZ2+V6OS7BGwvWsrEL1k
      m9GXYjx5wUlpBXELn18VTYi4D1OvpFdXkguREjZcHYCQdvJXfHbu/pl/rk1BAkEA
      k4JKnGpuD/edkLpnEIPjkr1bdjcpi6Z0ks2BAGYTT156wVd+taxvo0cmMnJAWJGv
      tunZCTZh2+Lf60pP70SvpwJAXiDR6M8tU1R9XUadF291Z9bBvtojajcoFMDQTJiq
      pNoMgyKp2BKE19JaVocDJX4Rzz/Iht0ClNndJws7pIbWag==
      -----END RSA PRIVATE KEY-----
  - path: "/run/wcnotify.sh"
    permissions: "0755"
    owner: "root"
    content: |
      #!/bin/bash
      /usr/bin/$wc_notify$ --data-binary '{"status": "SUCCESS", "reason": "Registry is ready , :)", "data": "OK"}'
  - path: "/etc/hosts"
    permissions: "0644"
    owner: "root"
    content: |
      127.0.0.1 localhost $hostname$
coreos:
  units:
    - name: format-ephemeral.service
      runtime: true
      command: start
      content: |
        [Unit]
        Description=Formats the ephemeral drive
        After=dev-vdb.device
        Requires=dev-vdb.device
        ConditionPathExists=!/var/lib/docker/registry
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/usr/sbin/wipefs -f /dev/vdb
        ExecStart=/usr/sbin/mkfs.ext4 -F /dev/vdb
    - name: var-lib-docker.mount
      command: start
      content: |
        [Unit]
        Description=Mount ephemeral to /var/lib/docker
        Requires=format-ephemeral.service
        After=format-ephemeral.service
        [Mount]
        What=/dev/vdb
        Where=/var/lib/docker
        Type=ext4
    - name: docker-registry.service
      command: start
      content: |
        [Unit]
        Description=Docker registry for basic images for k8s cluster
        After=docker.service
        Requires=docker.service

        [Service]
        Type=oneshot
        RemainAfterExit=yes
        TimeoutStartSec=0
        ExecStartPre=/usr/bin/mkdir -p /etc/docker/certs.d/$hostname$:5000
        ExecStartPre=/usr/bin/cp /home/root/registry_certs/domain.crt /etc/docker/certs.d/$hostname$:5000/ca.crt
        ExecStartPre=/usr/bin/systemctl restart docker
        ExecStartPre=-/usr/bin/docker kill registry
        ExecStartPre=-/usr/bin/docker rm registry
        ExecStartPre=/usr/bin/docker pull registry:2.5

        ExecStart=/usr/bin/docker run -d -p 5000:5000 -v /var/lib/docker/registry:/var/lib/registry -v /home/root/registry_certs:/certs -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key -e REGISTRY_STORAGE_CACHE_BLOBDESCRIPTOR=inmemory--restart=always --name registry registry:2.5
        ExecStop=/usr/bin/docker rm -f registry

        [Install]
        WantedBy=multi-user.target
    - name: docker.service
      drop-ins:
        - name: 09-opts-docker.conf
          content: |
            [Service]
            Environment="DOCKER_OPT_MTU=--mtu=$mtu$"
            Environment="DOCKER_OPTS=--registry-mirror=https://$hostname$:5000"
        - name: 10-wait-docker.conf
          content: |
            [Unit]
            After=var-lib-docker.mount
            Requires=var-lib-docker.mount
    - name: cfn-signal.service
      runtime: true
      command: start
      content: |
        [Unit]
        Description=Heat wait condition notifier
        After=docker-registry.service
        Requires=docker-registry.service
        [Service]
        Type=oneshot
        ExecStart=/run/wcnotify.sh