#cloud-config
coreos:
  units:
    - name: cfn-signal.service
      runtime: true
      command: start
      content: |
        [Service]
        ExecStart=/usr/bin/curl -sf -X PUT -H 'Content-Type: application/json' \
              --data-binary '{"Status": "SUCCESS", "Reason": "Setup complete", "Data": "OK", "UniqueId": "00000"}' \
              "$WAIT_HANDLE"
       
